name: 신규 구축 / 운영 변경 요청 (통합)
description: 그룹사 홈페이지 IT 서비스 요청 접수 폼 (PM 자동화용)
title: "[요청] 사이트명 - 요약"
body:
  - type: markdown
    attributes:
      value: |
        ## 그룹사 홈페이지 IT 요청 접수 (통합 폼)
        - 아래에서 **요청 유형**을 선택한 뒤, 해당 섹션을 작성해주세요.
        - 해당 없는 항목은 `N/A`로 기입해도 됩니다.

  # 0) 공통 정보
  - type: dropdown
    id: request_type
    attributes:
      label: 요청 유형
      options:
        - 신규 구축
        - 운영 변경
    validations:
      required: true

  - type: input
    id: site_name
    attributes:
      label: 사이트/법인명(또는 도메인)
      placeholder: 예) pressroom.nexon.com / 관계사 A / 넥슨재단
    validations:
      required: true

  - type: input
    id: requester
    attributes:
      label: 요청자(부서/이름)
      placeholder: 예) 홍보실 김OO
    validations:
      required: true

  - type: dropdown
    id: urgency
    attributes:
      label: 긴급도
      options:
        - 일반(2~4주 이상)
        - 빠름(1~2주)
        - 긴급(1주 이내)
    validations:
      required: true

  - type: dropdown
    id: pii
    attributes:
      label: 개인정보(PII) 수집/저장/처리 변경 여부
      options:
        - 없음
        - 있음
        - 모름(검토 필요)
    validations:
      required: true

  - type: dropdown
    id: auth
    attributes:
      label: 로그인/회원/권한 기능 영향 여부
      options:
        - 없음
        - 있음
        - 모름(검토 필요)
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: 요청 요약(한 문단)
      placeholder: 배경/목적/기대효과를 포함해 간단히
    validations:
      required: true

  - type: textarea
    id: links
    attributes:
      label: 참고 링크/자료
      placeholder: 예) 기존 페이지 URL, 기획서/디자인 링크, 경쟁사 참고, 스크린샷 등

  - type: markdown
    attributes:
      value: |
        ---
        ## ✅ [신규 구축] 섹션 (요청 유형이 "신규 구축"일 때 작성)

  # 1) 신규 구축 섹션
  - type: textarea
    id: new_scope
    attributes:
      label: (신규) 범위/사이트맵(IA)
      placeholder: 예) 메인/소개/뉴스룸/CSR/문의/다국어(KR/EN/JP) 등

  - type: dropdown
    id: new_language
    attributes:
      label: (신규) 다국어 필요 여부
      options:
        - 없음
        - 있음
        - 미정

  - type: textarea
    id: new_content
    attributes:
      label: (신규) 콘텐츠 준비 상태
      placeholder: 원고/이미지/번역/자료 제공 주체와 일정

  - type: textarea
    id: new_integrations
    attributes:
      label: (신규) 연동/외부 시스템
      placeholder: 예) GA/GTAG, CMS, CRM, 이메일 발송, CDN, SSO 등

  - type: textarea
    id: new_constraints
    attributes:
      label: (신규) 제약/선호사항
      placeholder: 예) 특정 CMS/인프라, 디자인 가이드, 도메인, 운영조직, 보안요건 등

  - type: markdown
    attributes:
      value: |
        ---
        ## ✅ [운영 변경] 섹션 (요청 유형이 "운영 변경"일 때 작성)

  # 2) 운영 변경 섹션
  - type: dropdown
    id: change_type
    attributes:
      label: (변경) 변경 유형
      options:
        - 콘텐츠/페이지 추가·수정
        - 기능 변경(폼/검색/다국어 등)
        - 정책/약관/개인정보처리방침 변경
        - 인프라/도메인/CDN/배포 변경
        - 성능/SEO/접근성 개선
        - 기타

  - type: textarea
    id: asis_tobe
    attributes:
      label: (변경) AS-IS / TO-BE
      placeholder: 현재 상태(문제/요구)와 변경 후 모습을 구체적으로 (가능하면 스크린샷/URL 포함)

  - type: dropdown
    id: impact
    attributes:
      label: (변경) 서비스 영향도(리스크)
      options:
        - 낮음(단순 문구/이미지 등)
        - 중간(페이지 추가, 경미한 기능)
        - 높음(폼/로그인/SEO/배포/인프라 등)

  - type: textarea
    id: release_window
    attributes:
      label: (변경) 희망 반영일/배포창
      placeholder: 예) 12/24 18:00 이후 / 특정 캠페인 시작 전 등

  - type: checkboxes
    id: done_definition
    attributes:
      label: 완료 기준(가능하면 체크)
      options:
        - label: QA/검증 완료가 필요함
        - label: 운영 공지/릴리즈노트가 필요함
        - label: 롤백(원복) 플랜이 필요함
        - label: 법무/보안/개인정보 검토가 필요함
